### PR TITLE
#161430953 unit tests for the application components (Authentication, Product, Sales)

### PR DESCRIPTION
**Pull request by waracci**
#### What does this PR do?

1. Create Basic Repository structure

2. Create Github Repository
3. Set Up Postgres with psycopg2 adapter
4. Create a BaseTest Class for common and shared methods
5. Implement Authentication test Suite
6. Implement Product Tests
7. Implement Sales Tests

#### What are the relevant pivotal tracker stories?
[#161430953](https://www.pivotaltracker.com/story/show/161430953)

### CODE REVIEW

**Comment by kwanj-k** [comment]
I think you forgot and called it v1 again in your structure

**Comment by waracci** [comment]
I had actually thought about it then I concluded that it would look off to have a v2 folder without the v1 folder.

**Comment by kwanj-k** [comment]
Valid, just confused me though

**Review by dotNesh — APPROVED** [review]
LGTM

**Comment by Collins33** [comment]
Looks good to me

**Pull request merged**
